name: Build Android Release AAB

on:
  push:
    branches:
      - main # Se dispara cuando haces push a la rama 'main'
      # O puedes usar tags:
      # tags:
      #   - 'v*' # Se dispara cuando creas un tag que empieza con 'v' (ej. v1.0.0)
  workflow_dispatch: # Permite disparar el workflow manualmente desde la UI de GitHub Actions

jobs:
  build-android:
    runs-on: ubuntu-latest # Usar una máquina virtual Ubuntu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Acción para descargar tu código

      - name: Set up JDK 17
        uses: actions/setup-java@v4 # Acción para configurar Java (necesario para Gradle y keytool)
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Acción para configurar Node.js (para npm y Capacitor)
        with:
          node-version: '20' # Usa una versión LTS de Node.js
          cache: 'npm' # Cachear dependencias npm

      - name: Install npm dependencies
        run: npm ci # 'ci' es más rápido y seguro para CI que 'install'

      - name: Sync Capacitor Android project
        run: npx cap sync android # Sincroniza los assets web con la plataforma Android

      - name: Decode Keystore and Setup Keystore File
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo "Decoding Keystore..."
          mkdir -p android/app # Asegurar que la carpeta exista para el keystore
          echo $ANDROID_KEYSTORE_BASE64 | base64 --decode > android/app/release-keystore.jks
          echo "Keystore decoded to android/app/release-keystore.jks"

      # --- AÑADIR ESTE PASO PARA DAR PERMISOS DE EJECUCIÓN A GRADLEW ---
      - name: Make gradlew executable
        working-directory: ./android # Ejecutar desde la carpeta 'android'
        run: chmod +x ./gradlew
      # --- FIN PASO AÑADIDO ---

      - name: Build Android Release App Bundle
        env:
          ANDROID_KEYSTORE_FILE: "release-keystore.jks" # Nombre del archivo keystore dentro de android/app/
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        working-directory: ./android # Ejecutar el siguiente comando desde la carpeta 'android'
        run: ./gradlew bundleRelease # Construye el AAB firmado

      - name: Upload Release AAB as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zodiac-gym-app-release-aab # Nombre del artefacto
          path: android/app/build/outputs/bundle/release/app-release.aab # Ruta al AAB
          retention-days: 7
